services:
  mysql:
    image: mysql:8
    restart: always
#    将主机的 3307 端口映射到容器的 3306 端口，这样可以通过主机的 3307 端口访问容器内的 MySQL 服务。
    ports:
      - '3307:3306'
  # 将主机的 ./mysql/data/ 目录挂载到容器的 /var/lib/mysql/ 目录，实现数据持久化，避免容器销毁后数据丢失。
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${mysql_pwd}
      MYSQL_DATABASE: lab_management_hmy
#   在容器启动时执行的命令，设置 MySQL 的最大连接数为 2500。
    command:
      --max_connections=2500
    healthcheck:
#      检查命令，尝试以 root 用户身份登录 MySQL 并执行 select 1; 语句。
      # test: mysql --user=root --password=1157 -e "select 1;"
      test: mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e "select 1;"
#      检查间隔时间为 10 秒
      interval: 10s
#      检查超时时间为 3 秒。
      timeout: 3s
#      重试次数为 3 次。
      retries: 3

  openjdk:
    image: openjdk:21
    restart: always
#    设置服务依赖关系，openjdk 服务依赖于 mysql 服务，并且只有当 mysql 服务处于健康状态时才会启动。
    depends_on:
      mysql:
        condition: service_healthy
#        将容器的 8080 端口暴露出来，但没有指定主机端口映射，通常用于内部网络通信。
    ports:
      - '8080'
#    将主机的 ./openjdk/ 目录挂载到容器的 /home/ 目录，方便将应用程序的 JAR 文件挂载到容器中。
    volumes:
      - ./openjdk/:/home/
    environment:
      dhost: mysql:3306
      dusername: root
      dpassword: ${mysql_pwd}
#      dingtalk_appkey: ${dingtalk_appkey}
#      dingtalk_appsecret: ${dingtalk_appsecret}
#      dingtalk_agentid: ${dingtalk_appkey}
      secretkey: ${secretkey}
      TZ: Asia/Shanghai
#      在容器启动时执行的命令，运行 Spring Boot 应用程序的 JAR 文件，并指定使用生产环境配置。
    command: java -jar /home/laboratory-booking-management-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

  nginx:
    image: nginx:1.25
    restart: always
#    设置服务依赖关系，nginx 服务依赖于 openjdk 服务，即 openjdk 服务启动后 nginx 服务才会启动。
    depends_on:
      - openjdk
#       将主机的 80 端口映射到容器的 80 端口，这样可以通过主机的 80 端口访问容器内的 Nginx 服务。
    ports:
      - '80:80'
    environment:
      - bhost=openjdk:8080
    volumes:
#    将主机的 ./nginx/html 目录以只读方式挂载到容器的 /usr/share/nginx/html 目录，用于存放静态网页文件。
      - ./nginx/html:/usr/share/nginx/html:ro
#     将主机的 ./nginx/templates 目录挂载到容器的 /etc/nginx/templates 目录，用于存放 Nginx 的配置模板文件。
      - ./nginx/templates:/etc/nginx/templates